import type { IconType } from "react-icons";
import { FaAws } from "react-icons/fa";
import { TbBrandAzure } from "react-icons/tb";
import {
  SiAnsible,
  SiCloudflare,
  SiDocker,
  SiExpress,
  SiFirebase,
  SiGit,
  SiGithub,
  SiGithubactions,
  SiGitlab,
  SiGrafana,
  SiGsap,
  SiJavascript,
  SiJenkins,
  SiKubernetes,
  SiLinux,
  SiMongodb,
  SiMysql,
  SiNextdotjs,
  SiNodedotjs,
  SiPrometheus,
  SiReact,
  SiRedux,
  SiStripe,
  SiTailwindcss,
  SiTerraform,
  SiTypescript,
  SiVite,
} from "react-icons/si";
import {
  Activity,
  Cloud,
  HardDrive,
  Network,
  Radar,
  Server,
  Shield,
  Workflow,
} from "lucide-react";

type AnyIcon = IconType | typeof Cloud;

const iconMap: Record<string, AnyIcon> = {
  "Microsoft Azure": TbBrandAzure,
  Azure: TbBrandAzure,
  "Azure Virtual Machines": Server,
  "Azure Virtual Network": Network,
  "VPN Gateway": Network,
  "Site-to-Site VPN": Network,
  "Application Gateway": Network,
  "Network Security Groups": Shield,
  "Azure Site Recovery": Shield,
  "Azure Backup": HardDrive,
  "Azure Monitor": Radar,
  "Log Analytics": Activity,
  "Azure Storage": HardDrive,
  "Recovery Services Vault": HardDrive,
  "Azure DNS": Network,
  "Azure Cost Management": Activity,
  "Azure networking": Network,
  "Azure security concepts": Shield,

  AWS: FaAws,
  EC2: FaAws,
  CloudWatch: FaAws,
  CloudFormation: FaAws,
  "AWS Cost Explorer": FaAws,
  "AWS networking fundamentals": FaAws,
  "Serverless concepts": FaAws,
  "AWS infrastructure": FaAws,

  Docker: SiDocker,
  Kubernetes: SiKubernetes,
  Jenkins: SiJenkins,
  "GitHub Actions": SiGithubactions,
  "GitLab CI/CD": SiGitlab,
  Terraform: SiTerraform,
  Ansible: SiAnsible,
  Git: SiGit,
  GitHub: SiGithub,
  Linux: SiLinux,
  "Shell Scripting": SiLinux,

  "TCP/IP": Network,
  DNS: Network,
  VPN: Network,
  NSG: Shield,
  Firewalls: Shield,
  Routing: Network,
  "Network Security": Shield,
  "Windows Server": Server,
  "Virtual Machines": Server,
  Storage: HardDrive,
  "Disk Management": HardDrive,
  Prometheus: SiPrometheus,
  Grafana: SiGrafana,
  Replication: Workflow,
  RTO: Activity,
  RPO: Activity,
  "Active-Passive DR": Shield,

  React: SiReact,
  "Next.js": SiNextdotjs,
  TypeScript: SiTypescript,
  JavaScript: SiJavascript,
  "Tailwind CSS": SiTailwindcss,
  Redux: SiRedux,
  Vite: SiVite,
  GSAP: SiGsap,
  "Node.js": SiNodedotjs,
  "Express.js": SiExpress,
  "REST APIs": SiNodedotjs,
  MongoDB: SiMongodb,
  MySQL: SiMysql,
  Cloudinary: SiCloudflare,
  Stripe: SiStripe,
  Clerk: SiFirebase,
  Stream: SiFirebase,
};

export function getSkillIcon(name: string): AnyIcon {
  if (iconMap[name]) return iconMap[name];
  const lower = name.toLowerCase();
  if (lower.includes("azure")) return TbBrandAzure;
  if (lower.includes("aws")) return FaAws;
  return Cloud;
}
